version: '2'

services:
    phpfpm:
        image: jengweb/php-fpm:7.1
        volumes:
            - /var/www/laravel-quickstart-test.com:/app
            - /var/dockers/laravel-quickstart-test.com/php-fpm:/bitnami/php-fpm
    mysqltest:
        image: jengweb/mysql:5.7
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_USER=my_user
            - MYSQL_PASSWORD=my_password
            - MYSQL_DATABASE=my_database
