version: '2'

services:
    nginx:
        image: jengweb/nginx:1.12
        depends_on:
            - phpfpm
        ports:
            - 8081:8080
        restart: always
        volumes:
            - /var/www/laravel-quickstart-internal.com:/app
            - /var/dockers/laravel-quickstart-internal.com/nginx:/bitnami/nginx
            - /var/dockers/laravel-quickstart-internal.com/logs:/opt/bitnami/nginx/logs
    phpfpm:
        image: jengweb/php-fpm:7.1
        restart: always
        volumes:
            - /var/www/laravel-quickstart-internal.com:/app
            - /var/dockers/laravel-quickstart-internal.com/php-fpm:/bitnami/php-fpm
